# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- deploy/ListApp

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

name: $(Date:yyyyMMdd)$(Rev:.r)

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'
    
- task: Android-Manifest-Version@1
  inputs:
    sourcePath: 'ListApp/ListApp.Android/Properties/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Date:yyyyMMdd)$(Rev:r)'
    versionName: '1.4.$(Build.BuildId)'
    printFile: true

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
