# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- deploy/ListApp

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
steps:
    
- script: | 
    export newNumber=$(Date:yyyyMMdd)$(Rev:r)
    echo "===== creating new variable ====="
    echo "##vso[task.setvariable variable=NEWBUILDNUMBER;]$newNumber"
    echo "===== creating new variable ====="
  displayName: 'Get New Build Number'

- script: |
    echo new build number $(NEWBUILDNUMBER)
  displayName: 'Display New Build Number'

- script: |
    echo "===== updating buildnumber ====="
    echo "##vso[build.updatebuildnumber]$NEWBUILDNUMBER"
    echo "===== updating buildnumber ====="
  displayName: 'Update Build Number'

- script: |
    echo "New Build Number is: $(Build.BuildNumber)"
  displayName: 'Display Updated Build Number'
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
