//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListApp.Resources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageChanged.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListCreated.
        /// </summary>
        internal static string ListCreated {
            get {
                return ResourceManager.GetString("ListCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDeleted.
        /// </summary>
        internal static string ListDeleted {
            get {
                return ResourceManager.GetString("ListDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListPermanentlyDeleted.
        /// </summary>
        internal static string ListPermanentlyDeleted {
            get {
                return ResourceManager.GetString("ListPermanentlyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListRestored.
        /// </summary>
        internal static string ListRestored {
            get {
                return ResourceManager.GetString("ListRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListShared.
        /// </summary>
        internal static string ListShared {
            get {
                return ResourceManager.GetString("ListShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListsSynced.
        /// </summary>
        internal static string ListsSynced {
            get {
                return ResourceManager.GetString("ListsSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggedInWithGoogle.
        /// </summary>
        internal static string LoggedInWithGoogle {
            get {
                return ResourceManager.GetString("LoggedInWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThemeChanged.
        /// </summary>
        internal static string ThemeChanged {
            get {
                return ResourceManager.GetString("ThemeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSignedOut.
        /// </summary>
        internal static string UserSignedOut {
            get {
                return ResourceManager.GetString("UserSignedOut", resourceCulture);
            }
        }
    }
}
