//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListApp.Resources.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListApp.Resources.Internationalization.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle bin.
        /// </summary>
        public static string MenuRecycleBin {
            get {
                return ResourceManager.GetString("MenuRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with ♥ by Jefferson Rocha &amp; Carla Marcondes.
        /// </summary>
        public static string PageAboutMessage {
            get {
                return ResourceManager.GetString("PageAboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Google.
        /// </summary>
        public static string PageAccountLoginWithGoogle {
            get {
                return ResourceManager.GetString("PageAccountLoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed out.
        /// </summary>
        public static string PageAccountSignedOut {
            get {
                return ResourceManager.GetString("PageAccountSignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string PageAccountSignOut {
            get {
                return ResourceManager.GetString("PageAccountSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string PageAccountSyncOnError {
            get {
                return ResourceManager.GetString("PageAccountSyncOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        public static string PageAccountSyncStarted {
            get {
                return ResourceManager.GetString("PageAccountSyncStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced!.
        /// </summary>
        public static string PageAccountSyncSuccessful {
            get {
                return ResourceManager.GetString("PageAccountSyncSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with cloud.
        /// </summary>
        public static string PageAccountSyncWithCloud {
            get {
                return ResourceManager.GetString("PageAccountSyncWithCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string PageAccountTitle {
            get {
                return ResourceManager.GetString("PageAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List deleted..
        /// </summary>
        public static string PageListItemsDeletedListMessage {
            get {
                return ResourceManager.GetString("PageListItemsDeletedListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List moved to trash..
        /// </summary>
        public static string PageListItemsMovedListToTrash {
            get {
                return ResourceManager.GetString("PageListItemsMovedListToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current list is empty..
        /// </summary>
        public static string PageListItemsNothingToShareMessageBody {
            get {
                return ResourceManager.GetString("PageListItemsNothingToShareMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to share.
        /// </summary>
        public static string PageListItemsNothingToShareMessageTitle {
            get {
                return ResourceManager.GetString("PageListItemsNothingToShareMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List restored..
        /// </summary>
        public static string PageListItemsPageRestoredMessage {
            get {
                return ResourceManager.GetString("PageListItemsPageRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        public static string PageListItemsPermanentlyDeleteMessageBody {
            get {
                return ResourceManager.GetString("PageListItemsPermanentlyDeleteMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete list {0}?.
        /// </summary>
        public static string PageListItemsPermanentlyDeleteMessageTitle {
            get {
                return ResourceManager.GetString("PageListItemsPermanentlyDeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore list.
        /// </summary>
        public static string PageListItemsRestoreButtonText {
            get {
                return ResourceManager.GetString("PageListItemsRestoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here....
        /// </summary>
        public static string PageListItemsTopEntryPlaceholder {
            get {
                return ResourceManager.GetString("PageListItemsTopEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New list.
        /// </summary>
        public static string PageListsNewListTitle {
            get {
                return ResourceManager.GetString("PageListsNewListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle bin.
        /// </summary>
        public static string PageListsRecycleBinTitle {
            get {
                return ResourceManager.GetString("PageListsRecycleBinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PageSettingsTitle {
            get {
                return ResourceManager.GetString("PageSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string SettingsAccountDescription {
            get {
                return ResourceManager.GetString("SettingsAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string SettingsAccountTitle {
            get {
                return ResourceManager.GetString("SettingsAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a new language.
        /// </summary>
        public static string SettingsLanguageDescription {
            get {
                return ResourceManager.GetString("SettingsLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an awesome new theme for the app.
        /// </summary>
        public static string SettingsThemeDescription {
            get {
                return ResourceManager.GetString("SettingsThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string SettingsThemeTitle {
            get {
                return ResourceManager.GetString("SettingsThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
